[0m14:18:19.634428 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125B582E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125E10D120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125E10CF10>]}


============================== 14:18:19.647909 | 535f0391-0b2a-4441-b61f-f4fc8bde0904 ==============================
[0m14:18:19.647909 [info ] [MainThread]: Running with dbt=1.7.9
[0m14:18:19.648909 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'debug': 'False', 'version_check': 'True', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt init', 'static_parser': 'True', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:18:19.649910 [warn ] [MainThread]: [ConfigFolderDirectory]: Unable to parse dict {'dir': WindowsPath('C:/Users/Miguel/.dbt')}
[0m14:18:19.650908 [info ] [MainThread]: Creating dbt configuration folder at 
[0m14:18:52.266333 [debug] [MainThread]: Starter project path: C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\include\starter_project
[0m14:18:52.317314 [info ] [MainThread]: 
Your new dbt project "vinted_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m14:18:52.320313 [info ] [MainThread]: Setting up your profile.
[0m14:18:52.321314 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m14:18:52.323314 [debug] [MainThread]: Command `dbt init` failed at 14:18:52.323314 after 32.74 seconds
[0m14:18:52.324312 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125B582E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125E10DF00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002125E10E170>]}
[0m14:18:52.324312 [debug] [MainThread]: Flushing usage events
[0m14:49:16.867763 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F4E1F2710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F50D7CF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F50D7D7B0>]}


============================== 14:49:16.898763 | 0634922b-1f74-46e2-b969-0b12e8ab4f05 ==============================
[0m14:49:16.898763 [info ] [MainThread]: Running with dbt=1.7.9
[0m14:49:16.899763 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'debug': 'False', 'fail_fast': 'False', 'log_path': 'logs', 'warn_error': 'None', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt run', 'send_anonymous_usage_stats': 'True'}
[0m14:49:16.921764 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Miguel\Desktop\dataengineeringpr\vinted-orchestration\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:49:16.923764 [debug] [MainThread]: Command `dbt run` failed at 14:49:16.923764 after 0.08 seconds
[0m14:49:16.924763 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F4E1F2710>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F50D7CFD0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000028F50D7D060>]}
[0m14:49:16.924763 [debug] [MainThread]: Flushing usage events
[0m14:49:32.022537 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7171E34F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B719D6CE50>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B719D6DA20>]}


============================== 14:49:32.026567 | 4b732e3f-0edd-4f09-85a8-0b0296e3b21d ==============================
[0m14:49:32.026567 [info ] [MainThread]: Running with dbt=1.7.9
[0m14:49:32.027535 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'debug': 'False', 'warn_error': 'None', 'log_path': 'logs', 'version_check': 'True', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'introspect': 'True', 'log_format': 'default', 'target_path': 'None', 'invocation_command': 'dbt build', 'send_anonymous_usage_stats': 'True'}
[0m14:49:32.028536 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Miguel\Desktop\dataengineeringpr\vinted-orchestration\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:49:32.030566 [debug] [MainThread]: Command `dbt build` failed at 14:49:32.030566 after 0.03 seconds
[0m14:49:32.030566 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B7171E34F0>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B719D6CF10>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001B719D6CFA0>]}
[0m14:49:32.031536 [debug] [MainThread]: Flushing usage events
[0m22:00:54.922260 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026676782E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667930D120>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667930CEB0>]}


============================== 22:00:54.944463 | 7156eb45-126b-4e81-8254-262ea01ed238 ==============================
[0m22:00:54.944463 [info ] [MainThread]: Running with dbt=1.7.9
[0m22:00:54.945535 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'warn_error': 'None', 'fail_fast': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'log_path': 'logs', 'debug': 'False', 'version_check': 'True', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'introspect': 'True', 'log_format': 'default', 'invocation_command': 'dbt init', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:01:03.064729 [debug] [MainThread]: Starter project path: C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\include\starter_project
[0m22:01:03.338889 [info ] [MainThread]: 
Your new dbt project "vinted_pipeline" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m22:01:03.341876 [info ] [MainThread]: Setting up your profile.
[0m22:01:03.343880 [error] [MainThread]: Encountered an error:
Runtime Error
  No adapters available. Learn how to install an adapter by going to https://docs.getdbt.com/docs/connect-adapters#install-using-the-cli
[0m22:01:03.345880 [debug] [MainThread]: Command `dbt init` failed at 22:01:03.345880 after 8.46 seconds
[0m22:01:03.346876 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x0000026676782E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667930E020>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000002667930E170>]}
[0m22:01:03.346876 [debug] [MainThread]: Flushing usage events
[0m22:02:56.248315 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96F912E30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F97249CF70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F97249D840>]}


============================== 22:02:56.252315 | c6577d96-e92d-4030-95b3-f868f81f2fd9 ==============================
[0m22:02:56.252315 [info ] [MainThread]: Running with dbt=1.7.9
[0m22:02:56.253316 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'write_json': 'True', 'log_cache_events': 'False', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'fail_fast': 'False', 'warn_error': 'None', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'invocation_command': 'dbt run', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'target_path': 'None', 'static_parser': 'True', 'send_anonymous_usage_stats': 'True'}
[0m22:02:56.254315 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Miguel\Desktop\dataengineeringpr\vinted-orchestration\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m22:02:56.256315 [debug] [MainThread]: Command `dbt run` failed at 22:02:56.255315 after 0.03 seconds
[0m22:02:56.256315 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F96F912E30>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F97249D030>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x000001F97249D0C0>]}
[0m22:02:56.257315 [debug] [MainThread]: Flushing usage events
[0m00:00:46.920735 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A1772E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A4341B70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A4340A30>]}


============================== 00:00:47.140664 | 645b1d8b-6db1-4c9d-a1f6-7cee427ba968 ==============================
[0m00:00:47.140664 [info ] [MainThread]: Running with dbt=1.7.10
[0m00:00:47.142661 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\.dbt', 'version_check': 'True', 'debug': 'False', 'log_path': 'logs', 'warn_error': 'None', 'fail_fast': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'introspect': 'True', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'static_parser': 'True', 'target_path': 'None', 'invocation_command': 'dbt init dbt', 'send_anonymous_usage_stats': 'True'}
[0m00:01:08.521592 [debug] [MainThread]: Starter project path: C:\Users\Miguel\AppData\Local\Programs\Python\Python310\lib\site-packages\dbt\include\starter_project
[0m00:01:08.968298 [info ] [MainThread]: 
Your new dbt project "dbt_vinted" was created!

For more information on how to configure the profiles.yml file,
please consult the dbt documentation here:

  https://docs.getdbt.com/docs/configure-your-profile

One more thing:

Need help? Don't hesitate to reach out to us via GitHub issues or on Slack:

  https://community.getdbt.com/

Happy modeling!

[0m00:01:08.971297 [info ] [MainThread]: Setting up your profile.
[0m00:03:37.136889 [info ] [MainThread]: Profile dbt_vinted written to C:\Users\Miguel\.dbt\profiles.yml using target's profile_template.yml and your supplied values. Run 'dbt debug' to validate the connection.
[0m00:03:37.138922 [debug] [MainThread]: Command `dbt init` succeeded at 00:03:37.138922 after 170.34 seconds
[0m00:03:37.139891 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A1772E00>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A4341B70>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000250A43A5B70>]}
[0m00:03:37.139891 [debug] [MainThread]: Flushing usage events
[0m14:52:08.653595 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'start', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194F8C4E650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194FB7E5360>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194FB7E5150>]}


============================== 14:52:08.657596 | 80a25487-be7e-4f27-b641-0872dcee68a8 ==============================
[0m14:52:08.657596 [info ] [MainThread]: Running with dbt=1.7.10
[0m14:52:08.658596 [debug] [MainThread]: running dbt with arguments {'printer_width': '80', 'indirect_selection': 'eager', 'log_cache_events': 'False', 'write_json': 'True', 'partial_parse': 'True', 'cache_selected_only': 'False', 'profiles_dir': 'C:\\Users\\Miguel\\Desktop\\dataengineeringpr\\vinted-orchestration\\data_orchestration', 'version_check': 'True', 'warn_error': 'None', 'log_path': 'logs', 'fail_fast': 'False', 'debug': 'False', 'use_colors': 'True', 'use_experimental_parser': 'False', 'no_print': 'None', 'quiet': 'False', 'log_format': 'default', 'static_parser': 'True', 'invocation_command': 'dbt deps --project-dir C:\\Users\\Miguel\\Desktop\\dataengineeringpr\\vinted-orchestration\\data_orchestration --profiles-dir C:\\Users\\Miguel\\Desktop\\dataengineeringpr\\vinted-orchestration\\data_orchestration -t dev', 'introspect': 'True', 'target_path': 'None', 'warn_error_options': 'WarnErrorOptions(include=[], exclude=[])', 'send_anonymous_usage_stats': 'True'}
[0m14:52:08.659596 [error] [MainThread]: Encountered an error:
Runtime Error
  No dbt_project.yml found at expected path C:\Users\Miguel\Desktop\dataengineeringpr\vinted-orchestration\data_orchestration\dbt_project.yml
  Verify that each entry within packages.yml (and their transitive dependencies) contains a file named dbt_project.yml
  
[0m14:52:08.660595 [debug] [MainThread]: Command `dbt deps` failed at 14:52:08.660595 after 0.03 seconds
[0m14:52:08.661596 [debug] [MainThread]: Sending event: {'category': 'dbt', 'action': 'invocation', 'label': 'end', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194F8C4E650>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194FB7E5390>, <snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x00000194FB7E53F0>]}
[0m14:52:08.661596 [debug] [MainThread]: Flushing usage events
